name: ci-command

on:
  pull_request_review:
  pull_request_review_comment:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: write
  pull-requests: write

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
  command-validation:
    if: startsWith(github.event.comment.body, '/test tav')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      versions: ${{ steps.transform.outputs.versions }}
      modules: ${{ steps.transform.outputs.modules }}
    steps:
      - name: Validate github comment
        uses: elastic/apm-pipeline-library/.github/actions/validate-github-comment@main

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - id: transform
        name: Transform comment to the supported matrix
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')

            let modules, versions
            try {
              const matrix = JSON.parse(fs.readFileSync('./matrix.json'))
              versions = matrix.versions
              modules = matrix.modules
            } catch (err) {
              core.setFailed(`Error loading './matrix.json': ${err}`)
              return
            }
            const comment = context.payload.comment.body
            if (comment !== '/test tav') {
              const regex = /\/test tav ([^\s]+)(\s*)([^\s]*)/
              const match = comment.match(regex)
              if (!match) {
                core.setFailed(`Incorrect comment, please use /test tav(\\s(module1,...,moduleN)?(\\s)?(node1,...,nodeN)?)?'`)
                return
              }
              if (match[1]) {
                if (match[1] !== 'all') {
                  modules = match[1].split(',')
                }
              }
              if (match[3]) {
                versions = match[3].split(',')
              }
            }
            core.setOutput('modules', modules)
            core.setOutput('versions', versions)

      - name: Notify - failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              ...context.repo,
              comment_id: context.payload.comment.id,
              content: '-1',
            })

  test-tav:
    needs: command-validation
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        node: ${{ fromJSON(needs.command-validation.outputs.versions) }}
        module: ${{ fromJSON(needs.command-validation.outputs.modules) }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: echo '"${{ matrix.module }}" "${{ matrix.node }}"'

      ##
      ## POST-BUILD notifications
      ##
      - name: Notify - success
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              ...context.repo,
              comment_id: context.payload.comment.id,
              content: 'heart',
            })

      - name: Notify - failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              ...context.repo,
              comment_id: context.payload.comment.id,
              content: '-1',
            })
